import Head from "next/head";
import Home from "../containers/home";

function HomePage() {
  return (
    <>
      <Head>
        <title>IS-2022-IC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
}

export default HomePage;
